beats/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url

from beats import views as v

from beats_app import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.index, name = 'index'),
    # path('beats/', include('beats_app.urls', namespace = 'beats')),
    path('books/', include('books.urls', namespace = 'books')),
]

beats_app/urls.py
from django.urls import path

from beats_app import views

from django.conf.urls import url

app_name = 'beats'

urlpatterns = [

    #path('labels/', views.LabelListView.as_view(), name = 'labels'),
    #path('beats/<label>', views.LabelBeatListView.as_view(), name = 'beats'),
    #path('create_label/', views.LabelCreateView.as_view(), name = 'create_label'),
    
]

books/urls.py
from django.urls import path

from books import views

from django.conf.urls import url

app_name = 'books'

urlpatterns = [

    path('create_author/', views.AuthorCreateView.as_view(), name="create_author"),
    path('authors_list/', views.AuthorListView.as_view(), name="authors_list"),
    path('create_book/', views.BookCreateView.as_view(), name="create_book"),
    path('booksbypublisher/<publisher>', views.BookByPublisherView.as_view(), name = 'booksbypublisher'),
    path('publisherdetailview/<pk>/', views.PublisherDetailView.as_view(), name='publisherdetailview'),
    path('view_authors/', views.view_authors, name = "view_authors"),
    
]

beats_app/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
'''

class Beat(models.Model):
	title = models.CharField(max_length = 32)
	author = models.CharField(max_length = 32)
	published_on = models.TimeField()
	is_liked = models.BooleanField(default = False)
	user = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.title


	def like(self):
		self.is_liked = True

class Label(models.Model):
	name = models.CharField(max_length = 32)
	owner = models.CharField(max_length = 64)
	beat = models.ForeignKey(Beat, on_delete = models.CASCADE)

	def __str__(self):
		return self.name

'''

books/models.py
from django.db import models

from django.contrib.auth import get_user_model

from django.urls import reverse

User = get_user_model()

# Create your models here.

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index')

class Author(models.Model):
    salutation = models.CharField(max_length=10)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    headshot = models.ImageField(upload_to='author_headshots')

    def __str__(self):
        return self.name


    def get_absolute_url(self):
    	return reverse('index')

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
    	return self.title


    def get_absolute_url(self):
        return reverse('index')

beats/views.py
from django.shortcuts import render



def index(request):
	return render(request, 'index.html')

beats_app/views.py
from django.shortcuts import render

from django.views.generic import ListView

# from beats_app.models import Beat, Label

from django.shortcuts import get_object_or_404

from django.views.generic.edit import CreateView

from django import forms

# Create your views here.

'''

class LabelListView(ListView):
	model = Label
	context_object_name = 'labels'
	template_name = 'beats_app/labels.html'

class LabelBeatListView(ListView):
	template_name = 'beats_app/beats_by_label.html'

	def get_queryset(self):
		self.label = get_object_or_404(Label, name=self.kwargs['label'])
		return Beat.objects.filter(label = self.label)

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super().get_context_data(**kwargs)

		# Add in the label
		context['label'] = self.label
		context['beats'] = Beat.objects.filter(label = self.label)
		return context

class LabelCreateView(CreateView):
	model = Label
	fields = ['name', 'owner']
	template_name = 'beats_app/create_label.html'
	widgets = {
		'name': forms.TextInput(attrs={'class': 'form-control'}),
		'owner': forms.TextInput(attrs={'class': 'form-control'})
		}

	def form_valid(self, form):
		self.object.beat = Beat.objects.all()
		return super().form_valid(form)



 def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)



'''

books/views.py
from django.shortcuts import render

from books.models import Publisher, Book, Author
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView

from django.shortcuts import get_object_or_404

from books.decorators import allowed_groups

# Create your views here.
# class cannot have decorators, they use mixin
class AuthorCreateView(CreateView):
	model = Author
	fields = ['name']

	template_name = 'books/author_create_form.html'


class AuthorListView(ListView):
	model = Author
	context_object_name = 'authors'
	template_name = 'books/authors_list.html'


class BookCreateView(CreateView):
	model = Book
	fields = ['title', 'publisher', 'authors', 'publication_date']
	template_name = 'books/create_book.html'

class BookByPublisherView(ListView):
	model = Book
	template_name = "books/booksbypublisher.html"

	def get_queryset(self):
		self.publisher = get_object_or_404(Publisher, name=self.kwargs['publisher'])
		return Book.objects.filter(publisher = self.publisher)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['publisher'] = self.publisher
		# Filtered books only by publisher name
		context['books'] = Book.objects.filter(publisher = self.publisher)
		return context

class PublisherDetailView(DetailView):
	model = Publisher

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		return context


@allowed_groups(['CRUD_Author'])
def view_authors(request):
	authors = Author.objects.all()

	context = {'authors': authors}

	return render(request, 'books/view_authors.html', context)

beats_app/templates/beats_app/beats_by_label.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block beats_by_label %}
	<br>
	<center><p>Beats by label: {{ label.name }}</p></center>
	<hr>

	{% for beat in beats %}
	<ol>
		<li><p>{{ beat.title }}</p></li>
	</ol>
	{% endfor %}
{% endblock %}

beats_app/templates/beats_app/create_label.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block create_label %}
<hr>
	<center><form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Create">
	</form></center>
{% endblock %}

beats_app/templates/beats_app/labels.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block labelsList %}
	
	<br>
	<center><p>Labels List</p></center>
	<hr>

	{% for label in labels %}
	<ol>
		<li><p><a href="{% url 'beats:beats' label.name %}">{{ label.name }}</a></p></li>
	</ol>
	{% endfor %}

{% endblock %}

books/templates/books/author_create_form.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block create_author %}
	<div class="container">
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="submit" name="submit">
		</form>

		
	</div>
{% endblock %}

books/templates/books/authors_list.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block authors_list %}
	<div class="container">
		{% for author in authors %}
			<p>Author name is: {{ author.name }}</p>
		{% endfor %}
	</div>
{% endblock %}

books/templates/books/booksbypublisher.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block booksbypublisher %}
	<br>
	<center><p><a href="{% url 'books:publisherdetailview' pk=publisher.id %}">Books by publisher: {{ publisher.name }}</a></p></center>
	<hr>

	{% for book in books %}
	<ol>
		<li><p>{{ book.title }}</p></li>
	</ol>
	{% endfor %}
{% endblock %}

books/templates/books/create_book.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block create_book %}
	<div class="container">
		<form method="POST">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <input type="submit" name="submit" value="submit">
	    </form>
		
	</div>
{% endblock %}

books/templates/books/publisher_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block publisher_detail %}
	<div class="container">

		{{ object.name }} is born in: {{ object.city }}
		
	</div>
{% endblock %}

books/templates/books/view_authors.html
{% extends 'base.html' %}


{% block view_authors %}

<center><div class="container">
	<p><abbr title="View Authors">View</abbr></p>

	{% for author in authors %}

	<p>{{ author.name }}</p>

	{% endfor %}
	
</div></center>
{% endblock %}

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Labels</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Create Label</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'books:create_author' %}">Create author</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

	<title></title>
</head>
<body>

	{% include '_navbar.html' %}

	
	<div class="container">
		{% block index %}
		{% endblock %}

		{% block create_author %}
		{% endblock %}

		{% block authors_list %}
		{% endblock %}

		{% block create_book %}

		{% endblock %}

		{% block booksbypublisher %}

		{% endblock %}

		{% block publisher_detail %}

		{% endblock %}

		{% block view_authors %}

		{% endblock %}
	</div>

	<!--

		{% block labelsList %}
		{% endblock %}

		{% block beats_by_label %}
		{% endblock %}

		{% block create_label %}
		{% endblock %}

	-->


</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}


{% block index %}

<p>I am the index</p>

<a href="{% url 'books:authors_list' %}">List of authors</a>
<a href="{% url 'books:create_book' %}">Create book</a>

{% endblock %}